OnlineShop/OnlineShopWebApp/Models/ClientContacts.cs
using System.ComponentModel.DataAnnotations;

namespace OnlineShopWebApp.Models
{
    public class ClientContacts
    {
        [Required(ErrorMessage = "Укажите имя")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Укажите фамилию")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Укажите номер телефона")]
        public string PhoneNumber { get; set; }
    }
}

OnlineShop/OnlineShopWebApp/Models/DeliveryAddress.cs
using System.ComponentModel.DataAnnotations;

namespace OnlineShopWebApp.Models
{
    public class DeliveryAddress
    {
        [Required(ErrorMessage = "Введите название города")]
        [StringLength(25, MinimumLength = 2, ErrorMessage = "Длина названия города: от 2-х до 25-ти символов")]
        public string СityName { get; set; }
        [Required(ErrorMessage = "Введите название улицы")]
        [StringLength(25, MinimumLength = 2, ErrorMessage = "Длина названия улицы: от 2-х до 25-ти символов")]
        public string StreetName { get; set; }
        [Required(ErrorMessage = "Укажите номер дома")]
        public string HouseNumber { get; set; }
        public string FlatNumber { get; set; }
    }
}

OnlineShop/OnlineShopWebApp/Controllers/ThemeController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShopWebApp.Models;

namespace OnlineShopWebApp.Controllers
{
    public class ThemeController : Controller
    {
        public IActionResult UpdateThemeOnDark()
        {
            Constants.Theme = Theme.Dark;
            return Redirect(Constants.ReturnPathToCurrentPage);
        }
        public IActionResult UpdateThemeOnLight()
        {
            Constants.Theme = Theme.Light;
            return Redirect(Constants.ReturnPathToCurrentPage);
        }
    }
}

OnlineShop/OnlineShopWebApp/Views/Shared/Components/AddProductToCart/AddProductToCartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace OnlineShopWebApp.Views.Shared.Components.AddProductToCart
{
    public class AddProductToCartViewComponent : ViewComponent
    {
        private readonly IProductsStorage productsStorage;
        private readonly ICartsStorage cartsStorage;
        public AddProductToCartViewComponent(IProductsStorage productsStorage, ICartsStorage cartsStorage)
        {
            this.productsStorage = productsStorage;
            this.cartsStorage = cartsStorage;
        }
        public IViewComponentResult Invoke(Guid productId)
        {
            var product = productsStorage.TryGetProductById(productId);
            var cart = cartsStorage.TryGetByUserId(Constants.UserId);
            ViewBag.ExistsInCart = cart.Items.FirstOrDefault(cartItem => cartItem.Product.Equals(product)) is null;
            return View("AddProductToCart", product);
        }
    }
}

OnlineShop/OnlineShopWebApp/Views/Shared/Components/AddProductToCartFromComparison/AddProductToCartFromComparisonViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace OnlineShopWebApp.Views.Shared.Components.AddProductToCartFromComparison
{
    public class AddProductToCartFromComparisonViewComponent : ViewComponent
    {
        private readonly IProductsStorage productsStorage;
        private readonly ICartsStorage cartsStorage;
        public AddProductToCartFromComparisonViewComponent(IProductsStorage productsStorage, ICartsStorage cartsStorage)
        {
            this.productsStorage = productsStorage;
            this.cartsStorage = cartsStorage;
        }
        public IViewComponentResult Invoke(Guid productId)
        {
            var product = productsStorage.TryGetProductById(productId);
            var cart = cartsStorage.TryGetByUserId(Constants.UserId);
            ViewBag.ExistsInCart = cart.Items.FirstOrDefault(cartItem => cartItem.Product.Equals(product)) is null;
            return View("AddProductToCartFromComparison", product);
        }
    }
}

OnlineShop/OnlineShopWebApp/Views/Shared/Components/AddProductToCartFromProductPage/AddProductToCartFromProductPageViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace OnlineShopWebApp.Views.Shared.Components.AddProductToCartFromProductPage
{
    public class AddProductToCartFromProductPageViewComponent : ViewComponent
    {
        private readonly IProductsStorage productsStorage;
        private readonly ICartsStorage cartsStorage;
        public AddProductToCartFromProductPageViewComponent(IProductsStorage productsStorage, ICartsStorage cartsStorage)
        {
            this.productsStorage = productsStorage;
            this.cartsStorage = cartsStorage;
        }
        public IViewComponentResult Invoke(Guid productId)
        {
            var product = productsStorage.TryGetProductById(productId);
            var cart = cartsStorage.TryGetByUserId(Constants.UserId);
            ViewBag.ExistsInCart = cart.Items.FirstOrDefault(cartItem => cartItem.Product.Equals(product)) is null;
            return View("AddProductToCartFromProductPageDark", product);
        }
    }
}

OnlineShop/OnlineShopWebApp/Views/Shared/Components/AddProductToComparison/AddProductToComparisonViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;

namespace OnlineShopWebApp.Views.Shared.Components.AddProductToComparison
{
    public class AddProductToComparisonViewComponent : ViewComponent
    {
        private readonly IProductsStorage productsStorage;
        private readonly IProductsComparisonStorage comparisonStorage;
        public AddProductToComparisonViewComponent(IProductsStorage productsStorage, IProductsComparisonStorage comparisonStorage)
        {
            this.productsStorage = productsStorage;
            this.comparisonStorage = comparisonStorage;
        }
        public IViewComponentResult Invoke(Guid productId)
        {
            var product = productsStorage.TryGetProductById(productId);
            var item = comparisonStorage.TryGetByUserId(Constants.UserId);
            ViewBag.Comparison = item.Products;
            return View("AddProductToComparison", product);
        }
    }
}

OnlineShop/OnlineShopWebApp/Views/Shared/Components/AddProductToComparisonFromProductPage/AddProductToComparisonFromProductPageViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;

namespace OnlineShopWebApp.Views.Shared.Components.AddProductToComparisonFromProductPage
{
    public class AddProductToComparisonFromProductPageViewComponent : ViewComponent
    {
        private readonly IProductsStorage productsStorage;
        private readonly IProductsComparisonStorage comparisonStorage;
        public AddProductToComparisonFromProductPageViewComponent(IProductsStorage productsStorage, IProductsComparisonStorage comparisonStorage)
        {
            this.productsStorage = productsStorage;
            this.comparisonStorage = comparisonStorage;
        }
        public IViewComponentResult Invoke(Guid productId)
        {
            var product = productsStorage.TryGetProductById(productId);
            var item = comparisonStorage.TryGetByUserId(Constants.UserId);
            ViewBag.Comparison = item.Products;
            return View("AddProductToComparisonFromProductPageDark", product);
        }
    }
}

OnlineShop/OnlineShopWebApp/Views/Shared/Components/AddProductToFavourites/AddProductToFavouritesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;

namespace OnlineShopWebApp.Views.Shared.Components.AddProductToFavourites
{
    public class AddProductToFavouritesViewComponent : ViewComponent
    {
        private readonly IProductsStorage productsStorage;
        private readonly IFavouritesStorage favouritesStorage;
        public AddProductToFavouritesViewComponent(IProductsStorage productsStorage, IFavouritesStorage favouritesStorage)
        {
            this.productsStorage = productsStorage;
            this.favouritesStorage = favouritesStorage;
        }
        public IViewComponentResult Invoke(Guid productId)
        {
            var product = productsStorage.TryGetProductById(productId);
            var item = favouritesStorage.TryGetByUserId(Constants.UserId);
            ViewBag.Comparison = item.Products;
            return View("AddProductToFavourites", product);
        }
    }
}

OnlineShop/OnlineShopWebApp/Views/Shared/Components/AddProductToFavouritesFromComparison/AddProductToFavouritesFromComparisonViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;

namespace OnlineShopWebApp.Views.Shared.Components.AddProductToFavouritesFromComparison
{
    public class AddProductToFavouritesFromComparisonViewComponent : ViewComponent
    {
        private readonly IProductsStorage productsStorage;
        private readonly IFavouritesStorage favouritesStorage;
        public AddProductToFavouritesFromComparisonViewComponent(IProductsStorage productsStorage, IFavouritesStorage favouritesStorage)
        {
            this.productsStorage = productsStorage;
            this.favouritesStorage = favouritesStorage;
        }
        public IViewComponentResult Invoke(Guid productId)
        {
            var product = productsStorage.TryGetProductById(productId);
            var item = favouritesStorage.TryGetByUserId(Constants.UserId);
            ViewBag.Comparison = item.Products;
            return View("AddProductToFavouritesFromComparison", product);
        }
    }
}

OnlineShop/OnlineShopWebApp/Views/Shared/Components/Cart/CartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShopWebApp.Models;

namespace OnlineShopWebApp.Views.Shared.Component.Cart
{
    public class CartViewComponent : ViewComponent
    {
        private readonly ICartsStorage cartsStorage;
        public CartViewComponent(ICartsStorage cartsStorage)
        {
            this.cartsStorage = cartsStorage;
        }
        public IViewComponentResult Invoke()
        {
            var cart = cartsStorage.TryGetByUserId(Constants.UserId);
            if (Constants.Theme.Equals(Theme.Light))
            {
                return View("Cart", cart.Amount);
            }
            return View("CartDark", cart.Amount);
        }
    }
}

OnlineShop/OnlineShopWebApp/Views/Shared/Components/Comparison/ComparisonViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShopWebApp.Models;

namespace OnlineShopWebApp.Views.Shared.Components.Comparison
{
    public class ComparisonViewComponent : ViewComponent
    {
        private readonly IProductsComparisonStorage comparisonStorage;
        public ComparisonViewComponent(IProductsComparisonStorage comparisonStorage)
        {
            this.comparisonStorage = comparisonStorage;
        }
        public IViewComponentResult Invoke()
        {
            var item = comparisonStorage.TryGetByUserId(Constants.UserId);
            if (Constants.Theme.Equals(Theme.Light))
            {
                return View("Comparison", item.Amount);
            }
            return View("ComparisonDark", item.Amount);
        }
    }
}

OnlineShop/OnlineShopWebApp/Views/Shared/Components/Favourites/FavouritesViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace OnlineShopWebApp.Views.Shared.Component.Favourites
{
    public class FavouritesViewComponent : ViewComponent
    {
        private readonly IFavouritesStorage favourites;
        public FavouritesViewComponent(IFavouritesStorage favourites)
        {
            this.favourites = favourites;
        }
        public IViewComponentResult Invoke()
        {
            var item = favourites.TryGetByUserId(Constants.UserId);
            return View("Favourites", item.Amount);
        }
    }
}

OnlineShop/OnlineShopWebApp/Views/Shared/ClientContacts.cshtml
@model ClientContacts

<fieldset style="background-color: rgba(225, 239, 242, 0.7); border-radius: 10px">
    <legend>Контактные данные получателя</legend>
    <div class="row align-items-center">
        <div class="col-4 offset-4" style="text-align: center; padding-bottom: 5px">
            <input style="text-align: center; width: 70%" placeholder="Введите имя" asp-for="FirstName" />
        </div>
        <div class="col-4" style="text-align: left">
            <span asp-validation-for="FirstName" />
        </div>
    </div>
    <div class="row align-items-center">
        <div class="col-4 offset-4" style="text-align: center; padding-bottom: 5px">
            <input style="text-align: center; width: 70%" placeholder="Введите фамилию" asp-for="LastName" />
        </div>
        <div class="col-4" style="text-align: left">
            <span asp-validation-for="LastName" />
        </div>
    </div>
    <div class="row align-items-center">
        <div class="col-4 offset-4" style="text-align: center; padding-bottom: 20px">
            <input style="text-align: center; width: 70%" placeholder="Введите номер телефона" asp-for="PhoneNumber" />
        </div>
        <div class="col-4" style="text-align: left; padding-bottom: 15px">
            <span asp-validation-for="PhoneNumber" />
        </div>
    </div>
</fieldset>

OnlineShop/OnlineShopWebApp/Views/Shared/DeliveryAddress.cshtml
@model DeliveryAddress

<fieldset style="background-color: rgba(225, 239, 242, 0.7); border-radius: 10px">
    <legend>Адрес получателя</legend>
    <div class="row align-items-center">
        <div class="col-4 offset-4" style="text-align: center; padding-bottom: 5px">
            <input style="text-align: center; width: 70%" placeholder="Введите название города" asp-for="СityName" />
        </div>
        <div class="col-4" style="text-align: left">
            <span asp-validation-for="СityName" />
        </div>
    </div>
    <div class="row align-items-center">
        <div class="col-4 offset-4" style="text-align: center; padding-bottom: 5px">
            <input style="text-align: center; width: 70%" placeholder="Введите название улицы" asp-for="StreetName" />
        </div>
        <div class="col-4" style="text-align: left">
            <span asp-validation-for="StreetName" />
        </div>
    </div>
    <div class="row align-items-center">
        <div class="col-4 offset-4" style="text-align: center; padding-bottom: 5px">
            <input style="text-align: center; width: 70%" placeholder="Введите номер дома" asp-for="HouseNumber" />
        </div>
        <div class="col-4" style="text-align: left">
            <span asp-validation-for="HouseNumber" />
        </div>
    </div>
    <div class="row align-items-center">
        <div class="col-4 offset-4" style="text-align: center; padding-bottom: 20px">
            <input style="text-align: center; width: 70%" placeholder="Введите номер квартиры" asp-for="FlatNumber" />
        </div>
    </div>
</fieldset>

OnlineShop/OnlineShopWebApp/Views/Shared/Footer.cshtml
<footer class="border-top footer text-muted">
    <div class="container text-center">
        <small>&copy; 2021 - 2022 Student Project. Made by Evgeniy Fisunov <i class="bi bi-vector-pen"></i></small>
    </div>
</footer>

OnlineShop/OnlineShopWebApp/Views/Shared/FooterDark.cshtml
<footer class="footer-dark footer text-muted">
    <div class="container text-center">
        <small>&copy; 2021 - 2022 Student Project. Made by Evgeniy Fisunov <i class="bi bi-vector-pen"></i></small>
    </div>
</footer>

OnlineShop/OnlineShopWebApp/Views/Shared/Header.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <div style="text-align: left">
                <a class="btn btn-primary" role="button"
                   asp-area=""
                   asp-controller="Home"
                   asp-action="Index">
                На главную <i class="bi bi-arrow-counterclockwise"></i></a>
                <span data-toggle="tooltip" title="Войти в аккаунт">
                    <a class="btn btn-primary" role="button"
                       asp-area=""
                       asp-controller="Account"
                       asp-action="Login">
                    <i class="bi bi-key-fill"></i><i class="bi bi-shield-lock"></i></a>
                </span>
                <a class="btn btn-dark" role="button"
                   asp-area="Admin"
                   asp-controller="Orders"
                   asp-action="Index">
                Администрирование <i class="bi bi-hammer"></i></a>
            </div>
            <div style="text-align: right">
                <div class="d-inline-block">
                    @await Html.PartialAsync("UpdateTheme")
                </div>
                <div class="d-inline-block" data-toggle="tooltip" title="Сравнение">
                    @await Component.InvokeAsync("Comparison")
                </div>
                <div class="d-inline-block" data-toggle="tooltip" title="Корзина">
                    @await Component.InvokeAsync("Cart")
                </div>
                <div class="d-inline-block" data-toggle="tooltip" title="Избранное">
                    @await Component.InvokeAsync("Favourites")
                </div>
            </div>
        </div>
    </nav>
</header>

OnlineShop/OnlineShopWebApp/Views/Shared/HeaderDark.cshtml
<header>
    <nav class="header-dark navbar navbar-expand-sm box-shadow mb-3">
        <div class="container">
            <div style="text-align: left">
                <a class="btn btn-primary btn-primary-glow-dark" role="button"
                   asp-area=""
                   asp-controller="Home"
                   asp-action="Index">
                На главную <i class="bi bi-arrow-counterclockwise"></i></a>
                <span data-toggle="tooltip" title="Войти в аккаунт">
                    <a class="btn btn-primary btn-primary-glow-dark" role="button"
                       asp-area=""
                       asp-controller="Account"
                       asp-action="Login">
                    <i class="bi bi-key-fill"></i><i class="bi bi-shield-lock"></i></a>
                </span>
                <a class="btn btn-light" role="button"
                   asp-area="Admin"
                   asp-controller="Orders"
                   asp-action="Index">
                Администрирование <i class="bi bi-hammer"></i></a>
            </div>
            <div style="text-align: right">
                <div class="d-inline-block">
                    @await Html.PartialAsync("UpdateTheme")
                </div>
                <div class="d-inline-block" data-toggle="tooltip" title="Сравнение">
                    @await Component.InvokeAsync("Comparison")
                </div>
                <div class="d-inline-block" data-toggle="tooltip" title="Корзина">
                    @await Component.InvokeAsync("Cart")
                </div>
                <div class="d-inline-block" data-toggle="tooltip" title="Избранное">
                    @await Component.InvokeAsync("Favourites")
                </div>
            </div>
        </div>
    </nav>
</header>

OnlineShop/OnlineShopWebApp/Views/Shared/UpdateTheme.cshtml
@if (Constants.Theme == 0)
{
    <div class="d-inline-block" data-toggle="tooltip" title="Выбрать тёмную тему">
        <a class="btn btn-dark" role="button"
           asp-area=""
           asp-controller="Theme"
           asp-action="UpdateThemeOnDark">
        <i class="bi bi-brightness-low" style="color: #1b6ec2"></i></a>
    </div>
}
else
{
    <div class="d-inline-block" data-toggle="tooltip" title="Выбрать светлую тему">
        <a class="btn btn-light" role="button"
           asp-area=""
           asp-controller="Theme"
           asp-action="UpdateThemeOnLight">
        <i class="bi bi-brightness-low" style="color: #1b6ec2"></i></a>
    </div>
}

OnlineShop/OnlineShopWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - Main</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.1/font/bootstrap-icons.css">
    </head>
    @if (Constants.Theme == 0)
    {
        <body style="background-image: url(/images/Theme_Light.jpg)">
            @await Html.PartialAsync("Header")
            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
            @await Html.PartialAsync("Footer")
            <script src="~/lib/jquery/dist/jquery.min.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
            @await Html.PartialAsync("_ValidationScriptsPartial")
            @RenderSection("Scripts", required: false)
        </body>
    }
    else
    {
        <body style="background-image: url(/images/Theme_Dark.jpg); background-size: 100% auto">
            @await Html.PartialAsync("HeaderDark")
            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
            @await Html.PartialAsync("FooterDark")
            <script src="~/lib/jquery/dist/jquery.min.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
            @await Html.PartialAsync("_ValidationScriptsPartial")
            @RenderSection("Scripts", required: false)
        </body>
    }
</html>