OnlineShop/OnlineShopWebApp/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace OnlineShopWebApp.Models
{
    public class Product
    {
        public Guid Id { get; set; }
        [Required(ErrorMessage = "Укажите имя")]
        [StringLength(25, MinimumLength = 2, ErrorMessage = "Длина имени: от 2-х до 25-ти символов")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Укажите стоимость")]
        [RegularExpression(@"^\d+(\.\d{1,2})?$", ErrorMessage = "Стоимость: от 1-ой до 2-х цифр после точки")]
        public decimal Cost { get; set; }
        public List<WorkLocation> Locations { get; set; }
        public string Documents { get; set; }
        public string Equipment { get; set; }
        public string Description { get; set; }
        public string ImagePath { get; }
        public Product()
        {
            Id = Guid.NewGuid();
        }
        public Product(string name, decimal cost, List<WorkLocation> locations, string documents, string equipment, string description, string imagePath) : this()
        {
            Name = name;
            Cost = cost;
            Locations = locations;
            Documents = documents;
            Equipment = equipment;
            Description = description;
            ImagePath = imagePath;
        }
    }
}

OnlineShop/OnlineShopWebApp/Areas/Admin/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShopWebApp.Models;
using System;
using System.Linq;

namespace OnlineShopWebApp.Areas.Controllers
{
    [Area("Admin")]
    public class ProductsController : Controller
    {
        private readonly IProductsStorage productsStorage;
        private readonly IWorkLocationsStorage locationsStorage;
        public ProductsController(IProductsStorage productsStorage, IWorkLocationsStorage locationsStorage)
        {
            this.productsStorage = productsStorage;
            this.locationsStorage = locationsStorage;
        }
        public IActionResult Index(int page = 1)
        {
            Constants.ReturnPathToCurrentPage = string.Intern($"~/admin/products/index?page={page}");
            productsStorage.ResetAdminSearchWord();
            int pageSize = 5;
            var сatalog = productsStorage.GetAllProducts()
                                         .AdminSortingProducts(Constants.AdminSortingProductsValue)
                                         .Skip((page - 1) * pageSize)
                                         .Take(pageSize)
                                         .ToList();
            var pageInfo = new PageInfo
            {
                PageNumber = page,
                PageSize = pageSize,
                TotalItems = productsStorage.GetAllProducts().Count()
            };
            var pnv = new PageNumberView
            {
                Products = сatalog,
                PageInfo = pageInfo
            };
            ViewBag.SearchWord = productsStorage.AdminSearchWord;
            ViewBag.SortingProductsValueView = Constants.AdminSortingProductsValueView;
            ViewBag.Catalog = productsStorage.GetAllProducts()
                                             .AdminSortingProducts(Constants.AdminSortingProductsValue)
                                             .ToList();
            ViewBag.Path = Constants.ReturnPathToCurrentPage;
            if (Constants.Theme.Equals(Theme.Light))
            {
                return View(pnv);
            }
            return View("IndexDark", pnv);
        }
        public IActionResult Search(int page = 1)
        {
            Constants.ReturnPathToCurrentPage = string.Intern($"~/admin/products/search?page={page}");
            int pageSize = 5;
            var searchWord = productsStorage.AdminSearchWord;
            var сatalog = productsStorage.SearchProductByName(searchWord)
                                         .AdminSortingProducts(Constants.AdminSortingProductsValue)
                                         .Skip((page - 1) * pageSize)
                                         .Take(pageSize)
                                         .ToList();
            var pageInfo = new PageInfo
            {
                PageNumber = page,
                PageSize = pageSize,
                TotalItems = productsStorage.SearchProductByName(searchWord).Count()
            };
            var pnv = new PageNumberView
            {
                Products = сatalog,
                PageInfo = pageInfo
            };
            ViewBag.SearchWord = searchWord;
            ViewBag.SortingProductsValueView = Constants.AdminSortingProductsValueView;
            ViewBag.Catalog = productsStorage.SearchProductByName(searchWord)
                                             .AdminSortingProducts(Constants.AdminSortingProductsValue)
                                             .ToList();
            ViewBag.Path = Constants.ReturnPathToCurrentPage;
            if (Constants.Theme.Equals(Theme.Light))
            {
                return View("Index", pnv);
            }
            return View("IndexDark", pnv);
        }

        [HttpPost]
        public IActionResult Search(string searchWord, int page = 1)
        {
            Constants.ReturnPathToCurrentPage = string.Intern($"~/admin/products/search?page={page}");
            int pageSize = 5;
            var сatalog = productsStorage.SearchProductByName(searchWord)
                                         .AdminSortingProducts(Constants.AdminSortingProductsValue)
                                         .Skip((page - 1) * pageSize)
                                         .Take(pageSize)
                                         .ToList();
            var pageInfo = new PageInfo
            {
                PageNumber = page,
                PageSize = pageSize,
                TotalItems = productsStorage.SearchProductByName(searchWord).Count()
            };
            var pnv = new PageNumberView
            {
                Products = сatalog,
                PageInfo = pageInfo
            };
            ViewBag.SearchWord = searchWord?.Trim();
            ViewBag.SortingProductsValueView = Constants.AdminSortingProductsValueView;
            ViewBag.Catalog = productsStorage.SearchProductByName(searchWord)
                                             .AdminSortingProducts(Constants.AdminSortingProductsValue)
                                             .ToList();
            ViewBag.Path = Constants.ReturnPathToCurrentPage;
            if (Constants.Theme.Equals(Theme.Light))
            {
                return View("Index", pnv);
            }
            return View("IndexDark", pnv);
        }

        public IActionResult Add()
        {
            Constants.ReturnPathToCurrentPage = string.Intern("~/admin/products/add");
            ViewBag.AllWorkLocations = locationsStorage.GetAllWorkLocations();
            if (Constants.Theme.Equals(Theme.Light))
            {
                return View();
            }
            return View("AddDark");
        }

        [HttpPost]
        public IActionResult Add(Product product, string[] locations)
        {
            if (!ModelState.IsValid)
            {
                return View(product);
            }
            productsStorage.AddProductWorkLocations(product, locations);
            productsStorage.AddProduct(product);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(Guid productId)
        {
            Constants.ReturnPathToCurrentPage = string.Intern($"~/admin/products/edit?productId={productId}");
            var product = productsStorage.TryGetProductById(productId);
            ViewBag.AllWorkLocations = locationsStorage.GetAllWorkLocations();
            if (Constants.Theme.Equals(Theme.Light))
            {
                return View(product);
            }
            return View("EditDark", product);
        }

        [HttpPost]
        public IActionResult Edit(Product product, string[] locations)
        {
            if (!ModelState.IsValid)
            {
                return View(product);
            }
            productsStorage.AddProductWorkLocations(product, locations);
            productsStorage.UpdateProduct(product);
            return RedirectToAction("Index");
        }

        public IActionResult Remove(Guid productId)
        {
            var product = productsStorage.TryGetProductById(productId);
            productsStorage.RemoveProduct(product);
            return Redirect(Constants.ReturnPathToCurrentPage);
        }
        public IActionResult Sorting(int sortingValue)
        {
            Constants.AdminSortingProductsValue = sortingValue;
            return Redirect(Constants.ReturnPathToCurrentPage);
        }
    }
}

OnlineShop/OnlineShopWebApp/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShopWebApp.Models;
using System;

namespace OnlineShopWebApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductsStorage productsStorage;
        public ProductController(IProductsStorage productsStorage)
        {
            this.productsStorage = productsStorage;
        }
        public IActionResult Index(Guid productId)
        {
            Constants.ReturnPathToCurrentPage = string.Intern($"~/product/index?productId={productId}");
            var product = productsStorage.TryGetProductById(productId);
            if (product is null) { return NotFound(); }
            ViewBag.ProductWorkLocations = productsStorage.GetProductWorkLocations(product);
            if (Constants.Theme.Equals(Theme.Light))
            {
                return View(product);
            }
            return View("IndexDark", product);
        }
    }
}

OnlineShop/OnlineShopWebApp/Areas/Admin/Views/Products/Index.cshtml
@model PageNumberView

@{
    ViewData["Title"] = "AdminProducts";
}

<form method="post">
    <div class="row">
        @await Html.PartialAsync("AdminLeftMenu")
        <div class="col-10">
            <div class="row" style="padding-bottom: 10px">
                <div class="col-12" style="height: 70px">
                    <div class="row" style="padding-bottom: 5px">
                        <div class="col-6" style="text-align: start">
                            <h3 style="margin-bottom: 0px">Список продуктов</h3>
                        </div>
                        <div class="col-6">
                            <div class="row justify-content-end">
                                @if (!string.IsNullOrEmpty(ViewBag.SearchWord))
                                {
                                    <div style="text-align: center; margin-top: 8px" data-toggle="tooltip" title="Сбросить">
                                        <a
                                           asp-area="Admin"
                                           asp-controller="Products"
                                           asp-action="Index">
                                        X</a>
                                    </div>
                                }
                                <div class="col-5" style="padding: 0px 0px 0px 5px; margin-top: 8px">
                                    <input type="text" style="text-align: center; width: 100%" placeholder="Поиск по имени" value="@ViewBag.SearchWord" name="searchWord" />
                                </div>
                                <div style="padding: 0px 5px 0px 5px; margin-top: 6px" data-toggle="tooltip" title="Начать поиск">
                                    <button class="btn btn-sm btn-primary" type="submit"
                                        asp-area="Admin"
                                        asp-controller="Products"
                                        asp-action="Search">
                                    <i class="bi bi-search"></i></button>
                                </div>
                                <div class="col-4" style="padding: 0px 0px 0px 0px; margin-top: 6px">
                                    <button class="btn btn-primary btn-sm dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Сортировать по</button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" style="padding: 0px 0px 0px 0px; margin: 0px 0px 0px 0px">
                                        <a class="dropdown-item"
                                           asp-area="Admin"
                                           asp-controller="Products"
                                           asp-action="Sorting"
                                           asp-route-sortingValue="1">
                                        <small>Возрастанию цены</small></a>
                                        <a class="dropdown-item"
                                           asp-area="Admin"
                                           asp-controller="Products"
                                           asp-action="Sorting"
                                           asp-route-sortingValue="-1">
                                        <small>Убыванию цены</small></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3" style="text-align: start">
                            <a
                               asp-area="Admin"
                               asp-controller="Products"
                               asp-action="Add">
                            Добавить новый продукт</a>
                        </div>
                        @if (!Model.Products.Count.Equals(0))
                        {
                            @if (ViewBag.Path.Contains("index"))
                            {
                                <div class="col-6 btn-group-sm text-sm-center">
                                    @Html.PageLinks(Model.PageInfo, pageNumber => Url.Action("Index", new { page = pageNumber }))
                                </div>
                            }
                            else
                            {
                                <div class="col-6 btn-group-sm text-sm-center">
                                    @Html.PageLinks(Model.PageInfo, pageNumber => Url.Action("Search", new { page = pageNumber }))
                                </div>
                            }
                        }
                        else
                        {
                            <div class="col-6"></div>
                        }
                        <div class="col-3">
                            <div class="col-12" style="text-align: right">
                                <small>@ViewBag.SortingProductsValueView</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            @if (Model.Products.Count.Equals(0))
            {
                if (ViewBag.Path.Contains("index"))
                {
                    <div class="row justify-content-center">
                        В настоящий момент товары отсутствуют.
                    </div>
                }
                else
                {
                    <div class="row justify-content-center">
                        По вашему запросу ничего не найдено.
                    </div>
                }
            }
            else
            {
                <table class="table" style="text-align: center">
                    <thead>
                        <tr>
                            <th>№</th>
                            <th>Имя мастера</th>
                            <th>Наименование услуги</th>
                            <th>Стоимость услуги</th>
                            <th colspan="2">Действия</th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (int i = 0; i < Model.Products.Count; i++)
                        {
                            <tr>
                                <td>@(ViewBag.Catalog.IndexOf(Model.Products[i]) + 1)</td>
                                <td>
                                    <a
                                       asp-area=""
                                       asp-controller="Product"
                                       asp-action="Index"
                                       asp-route-productId="@Model.Products[i].Id">
                                    @Model.Products[i].Name</a>
                                </td>
                                <td>Изготовление велосипедной рамы</td>
                                <td>@Model.Products[i].Cost</td>
                                <td>
                                    <a
                                       asp-area="Admin"
                                       asp-controller="Products"
                                       asp-action="Edit"
                                       asp-route-productId="@Model.Products[i].Id">
                                    Редактировать</a>
                                </td>
                                <td>
                                    <a href="#modal_form_@Model.Products[i].Id" data-toggle="modal">Удалить</a>
                                    <div class="modal" id="modal_form_@Model.Products[i].Id" tabindex="-1">
                                        <div class="modal-dialog" style="top: 25%">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title">Подтверждение действия</h5>
                                                </div>
                                                <div class="modal-body">
                                                    <p>Вы действительно хотите удалить товар <b>"@Model.Products[i].Name"</b>?</p>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-primary" data-dismiss="modal">Нет!</button>
                                                    <a class="btn btn-danger" role="button"
                                                       asp-area="Admin"
                                                       asp-controller="Products"
                                                       asp-action="Remove"
                                                       asp-route-productId="@Model.Products[i].Id">
                                                    Да.</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
        </div>
    </div>
</form>

OnlineShop/OnlineShopWebApp/Areas/Admin/Views/Products/IndexDark.cshtml
@model PageNumberView

@{
    ViewData["Title"] = "AdminProducts";
}

<form method="post">
    <div class="row">
        @await Html.PartialAsync("AdminLeftMenu")
        <div class="col-10">
            <div class="row" style="padding-bottom: 10px">
                <div class="col-12" style="height: 70px">
                    <div class="row" style="padding-bottom: 5px">
                        <div class="col-6 glow-font-dark" style="text-align: start">
                            <h3 style="margin-bottom: 0px">Список продуктов</h3>
                        </div>
                        <div class="col-6">
                            <div class="row justify-content-end">
                                @if (!string.IsNullOrEmpty(ViewBag.SearchWord))
                                {
                                    <div style="text-align: center; margin-top: 8px" data-toggle="tooltip" title="Сбросить">
                                        <a class="glow-reference-dark"
                                           asp-area="Admin"
                                           asp-controller="Products"
                                           asp-action="Index">
                                        X</a>
                                    </div>
                                }
                                <div class="col-5" style="padding: 0px 0px 0px 5px; margin-top: 8px">
                                    <input type="text" style="text-align: center; width: 100%" placeholder="Поиск по имени" value="@ViewBag.SearchWord" name="searchWord" />
                                </div>
                                <div style="padding: 0px 5px 0px 5px; margin-top: 6px" data-toggle="tooltip" title="Начать поиск">
                                    <button class="btn btn-sm btn-primary btn-primary-glow-dark" type="submit"
                                        asp-area="Admin"
                                        asp-controller="Products"
                                        asp-action="Search">
                                    <i class="bi bi-search"></i></button>
                                </div>
                                <div class="col-4" style="padding: 0px 0px 0px 0px; margin-top: 6px">
                                    <button class="btn btn-primary btn-primary-glow-dark btn-sm dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Сортировать по</button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" style="padding: 0px 0px 0px 0px; margin: 0px 0px 0px 0px">
                                        <a class="dropdown-item"
                                           asp-area="Admin"
                                           asp-controller="Products"
                                           asp-action="Sorting"
                                           asp-route-sortingValue="1">
                                        <small>Возрастанию цены</small></a>
                                        <a class="dropdown-item"
                                           asp-area="Admin"
                                           asp-controller="Products"
                                           asp-action="Sorting"
                                           asp-route-sortingValue="-1">
                                        <small>Убыванию цены</small></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3" style="text-align: start">
                            <a class="glow-reference-dark"
                               asp-area="Admin"
                               asp-controller="Products"
                               asp-action="Add">
                            Добавить новый продукт</a>
                        </div>
                        @if (!Model.Products.Count.Equals(0))
                        {
                            @if (ViewBag.Path.Contains("index"))
                            {
                                <div class="col-6 btn-group-sm text-sm-center">
                                    @Html.PageLinks(Model.PageInfo, pageNumber => Url.Action("Index", new { page = pageNumber }))
                                </div>
                            }
                            else
                            {
                                <div class="col-6 btn-group-sm text-sm-center">
                                    @Html.PageLinks(Model.PageInfo, pageNumber => Url.Action("Search", new { page = pageNumber }))
                                </div>
                            }
                        }
                        else
                        {
                            <div class="col-6"></div>
                        }
                        <div class="col-3">
                            <div class="col-12 glow-font-dark" style="text-align: right">
                                <small>@ViewBag.SortingProductsValueView</small>
                            </div>
                        </div>
                    </div>
                        </div>
            </div>
            @if (Model.Products.Count.Equals(0))
            {
                if (ViewBag.Path.Contains("index"))
                {
                    <div class="row justify-content-center glow-font-dark">
                        В настоящий момент товары отсутствуют.
                    </div>
                }
                else
                {
                    <div class="row justify-content-center glow-font-dark">
                        По вашему запросу ничего не найдено.
                    </div>
                }
            }
            else
            {
                <fieldset class="fieldset-table-dark">
                    <table class="table" style="text-align: center">
                        <thead class="glow-reference-dark">
                            <tr>
                                <th>№</th>
                                <th>Имя мастера</th>
                                <th>Наименование услуги</th>
                                <th>Стоимость услуги</th>
                                <th colspan="2">Действия</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (int i = 0; i < Model.Products.Count; i++)
                            {
                                <tr>
                                    <td class="glow-font-dark">@(ViewBag.Catalog.IndexOf(Model.Products[i]) + 1)</td>
                                    <td>
                                        <a class="glow-reference-dark"
                                           asp-area=""
                                           asp-controller="Product"
                                           asp-action="Index"
                                           asp-route-productId="@Model.Products[i].Id">
                                        @Model.Products[i].Name</a>
                                    </td>
                                    <td class="glow-font-dark">Изготовление велосипедной рамы</td>
                                    <td class="glow-font-dark">@Model.Products[i].Cost</td>
                                    <td>
                                        <a class="glow-reference-dark"
                                           asp-area="Admin"
                                           asp-controller="Products"
                                           asp-action="Edit"
                                           asp-route-productId="@Model.Products[i].Id">
                                        Редактировать</a>
                                    </td>
                                    <td>
                                        <a class="glow-reference-dark" href="#modal_form_@Model.Products[i].Id" data-toggle="modal">Удалить</a>
                                        <div class="modal" id="modal_form_@Model.Products[i].Id" tabindex="-1">
                                            <div class="modal-dialog" style="top: 25%">
                                                <div class="modal-content modal-background-dark">
                                                    <div class="modal-header glow-font-dark">
                                                        <h5 class="modal-title">Подтверждение действия</h5>
                                                    </div>
                                                    <div class="modal-body glow-font-dark">
                                                        <p>Вы действительно хотите удалить товар <b>"@Model.Products[i].Name"</b>?</p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-primary btn-primary-glow-dark-modal" data-dismiss="modal">Нет!</button>
                                                        <a class="btn btn-warning btn-warning-glow-dark" role="button"
                                                           asp-area="Admin"
                                                           asp-controller="Products"
                                                           asp-action="Remove"
                                                           asp-route-productId="@Model.Products[i].Id">
                                                        Да.</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </fieldset>
            }
        </div>
    </div>
</form>